# Generated by Django 2.1.5 on 2019-04-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
